execute:
	python main.py

 lint:
	python -m flake8

pytest-coverage:
	python -m pytest -v --cov-report html --cov=. --cov-config=.coveragerc tests/test_main.py 
pytest:
	python -m pytest -v tests/test_main.py